### PR TITLE
Return false upon attempt to delete non-existent key

### PR DESCRIPTION
**Pull request by alchzh**
would be nice for a little project I have right now.

### CODE REVIEW

**Comment by CreaturePhil** [comment]
@acz13 What is wrong with doing this?

``` js
if (!db('foo').get('something') return;
db('foo').delete('something');
```

**Comment by alchzh** [comment]
cleaner to do it in the library?

**Comment by CreaturePhil** [comment]
Having it return `this` or `false` can be confusing. I rather just have a new method called `has` like the JavaScript [Maps](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map).

``` js
if (db('foo').has('something') {
  db('foo').delete('something');
}
```

**Comment by alchzh** [comment]
that'd be good.

**Comment by CreaturePhil** [comment]
@acz13 hmm but the `get` method is essentially the same thing as the `has` method. why do you need a check for delete? you do know you can delete a key that is not in an object and it does nothing really

**Comment by alchzh** [comment]
@TheFenderStory is making me make a "jobs" command for Origin. It seems pretty odd to let the user delete a job from the list that doesn't exist and not return anything.

**Comment by CreaturePhil** [comment]
@acz13 Just use `db.get` to check and only delete if it exists. I want to keep the API as small as possible for simplicity and ease of use. Also if you do use the check often for a project, you can just abstract it out into a function.

``` js
function deleteProp(key, prop) {
  if (!db(key).get(prop) return false;
  return db(key).delete(prop);
}

if (deleteProp('foo', 'something') return sendReply('You do not have something to delete.');
```

**Pull request closed without merging**
